<?php

declare(strict_types=1);

$router->get('/', 'LandingController@index');
$router->get('/feed', 'ChatController@index', ['auth', 'activity']);
$router->get('/communities', 'ChatController@index', ['auth', 'activity']);
$router->get('/chat', 'ChatController@index', ['auth', 'activity']);
$router->post('/posts/create', 'ChatController@createPost', ['auth', 'csrf', 'ratelimit', 'activity']);
$router->post('/posts/delete', 'ChatController@deletePost', ['auth', 'csrf', 'activity']);
$router->post('/posts/like', 'ChatController@togglePostLike', ['auth', 'csrf', 'activity']);
$router->get('/posts/like-count', 'ChatController@getPostLikeCount', ['auth', 'activity']);
$router->get('/posts/comments', 'ChatController@listPostComments', ['auth', 'activity']);
$router->get('/posts/comments-count', 'ChatController@getPostCommentsCount', ['auth', 'activity']);
$router->post('/posts/comments', 'ChatController@createPostComment', ['auth', 'csrf', 'activity']);


$router->post('/chat/messages', 'ChatController@send', ['auth', 'csrf', 'ratelimit', 'activity']);
$router->post('/chat/messages/react', 'ChatController@toggleReaction', ['auth', 'csrf', 'activity']);
$router->post('/chat/messages/pin', 'ChatController@togglePin', ['auth', 'csrf', 'activity']);
$router->post('/chat/messages/delete', 'ChatController@deleteMessage', ['auth', 'csrf', 'activity']);
$router->post('/chat/messages/report', 'ChatController@reportMessage', ['auth', 'csrf', 'ratelimit', 'activity']);
$router->post('/chat/rooms', 'ChatController@createRoom', ['auth', 'csrf', 'activity']);
$router->get('/chat/stream', 'ChatController@stream', ['auth', 'activity']);
$router->post('/chat/typing', 'ChatController@typing', ['auth', 'csrf', 'activity']);
$router->post('/chat/recording', 'ChatController@recording', ['auth', 'csrf', 'activity']);

$router->post('/communities/join', 'ChatController@joinCommunity', ['auth', 'csrf', 'activity']);
$router->get('/notifications', 'ChatController@notifications', ['auth', 'activity']);
$router->get('/search', 'SearchController@index', ['auth', 'activity']);
$router->get('/login', 'AuthController@login', ['guest']);
$router->post('/login', 'AuthController@authenticate', ['guest', 'csrf', 'ratelimit']);
$router->get('/signup', 'AuthController@signup', ['guest']);
$router->post('/signup', 'AuthController@store', ['guest', 'csrf', 'ratelimit']);
$router->get('/forgot-password', 'AuthController@forgotPassword', ['guest']);
$router->post('/forgot-password', 'AuthController@sendResetLink', ['guest', 'csrf', 'ratelimit']);
$router->get('/reset-password', 'AuthController@resetPassword', ['guest']);
$router->post('/reset-password', 'AuthController@updatePassword', ['guest', 'csrf']);
$router->post('/logout', 'AuthController@logout', ['auth', 'csrf']);
$router->get('/profile', 'ProfileController@index', ['auth']);
$router->post('/profile', 'ProfileController@update', ['auth', 'csrf']);
$router->get('/settings', 'SettingsController@index', ['auth']);
$router->post('/settings', 'SettingsController@update', ['auth', 'csrf']);
$router->get('/users', 'UsersController@index', ['auth']);

$router->post('/users/dm-request', 'UsersController@requestDm', ['auth', 'csrf', 'activity']);
$router->post('/users/dm-request/respond', 'UsersController@respondDm', ['auth', 'csrf', 'activity']);
$router->post('/users/block', 'UsersController@blockUser', ['auth', 'csrf', 'activity']);
$router->post('/users/unblock', 'UsersController@unblockUser', ['auth', 'csrf', 'activity']);
$router->get('/admin/auth', 'AdminController@auth', ['auth']);
$router->post('/admin/auth', 'AdminController@verify', ['auth', 'csrf']);
$router->get('/admin', 'AdminController@redirectToAuth', ['auth']);
$router->get('/admin/dashboard', 'CentralAdminController@index', ['auth']);
$router->get('/admin/users', 'AdminController@users', ['auth']);
$router->post('/admin/users/create', 'AdminController@createUser', ['auth', 'csrf']);
$router->post('/admin/users/update', 'AdminController@updateUser', ['auth', 'csrf']);
$router->post('/admin/users/ban-toggle', 'AdminController@toggleBan', ['auth', 'csrf']);
$router->post('/admin/users/mute', 'AdminController@muteUser', ['auth', 'csrf']);
$router->post('/admin/users/unmute', 'AdminController@unmuteUser', ['auth', 'csrf']);
$router->post('/admin/users/import', 'AdminController@importUsers', ['auth', 'csrf']);
$router->get('/admin/chats', 'AdminController@chats', ['auth']);
$router->post('/admin/messages/delete', 'AdminController@deleteMessage', ['auth', 'csrf']);
$router->post('/admin/broadcast', 'AdminController@broadcast', ['auth', 'csrf']);
$router->post('/admin/reports/update', 'AdminController@updateReport', ['auth', 'csrf']);
$router->get('/admin/audit-logs', 'AdminController@auditLogs', ['auth']);
$router->get('/admin/audit-logs/export', 'AdminController@exportAuditLogs', ['auth']);
$router->get('/admin/settings', 'AdminController@settings', ['auth']);
$router->post('/admin/settings', 'AdminController@saveSettings', ['auth', 'csrf']);
$router->post('/admin/invites/create', 'AdminController@createInvite', ['auth', 'csrf']);
$router->get('/admin/rooms', 'RoomAdminController@index', ['auth']);
$router->post('/admin/rooms/update', 'RoomAdminController@update', ['auth', 'csrf']);
$router->post('/admin/rooms/delete', 'RoomAdminController@delete', ['auth', 'csrf']);
$router->post('/admin/rooms/create', 'AdminController@createRoom', ['auth', 'csrf']);
$router->get('/central-admin', 'CentralAdminController@index', ['auth']);
$router->get('/central-admin/dashboard', 'CentralAdminController@index', ['auth']);
$router->get('/central-admin/users', 'CentralAdminController@users', ['auth']);
$router->post('/central-admin/users/create', 'CentralAdminController@createUser', ['auth', 'csrf']);
$router->post('/central-admin/users/update', 'CentralAdminController@updateUser', ['auth', 'csrf']);
$router->post('/central-admin/users/ban-toggle', 'CentralAdminController@toggleBan', ['auth', 'csrf']);
$router->post('/central-admin/users/mute', 'CentralAdminController@muteUser', ['auth', 'csrf']);
$router->post('/central-admin/users/unmute', 'CentralAdminController@unmuteUser', ['auth', 'csrf']);
$router->post('/central-admin/users/import', 'CentralAdminController@importUsers', ['auth', 'csrf']);
$router->get('/central-admin/rooms', 'CentralAdminController@rooms', ['auth']);
$router->post('/central-admin/rooms/create', 'CentralAdminController@createRoom', ['auth', 'csrf']);
$router->post('/central-admin/rooms/update', 'CentralAdminController@updateRoom', ['auth', 'csrf']);
$router->post('/central-admin/rooms/delete', 'CentralAdminController@deleteRoom', ['auth', 'csrf']);
$router->get('/central-admin/audit-logs', 'CentralAdminController@auditLogs', ['auth']);
$router->get('/central-admin/audit-logs/export', 'CentralAdminController@exportAuditLogs', ['auth']);
$router->get('/central-admin/settings', 'CentralAdminController@settings', ['auth']);
$router->post('/central-admin/settings', 'CentralAdminController@saveSettings', ['auth', 'csrf']);
$router->post('/central-admin/invites/create', 'CentralAdminController@createInvite', ['auth', 'csrf']);
$router->post('/central-admin/broadcast', 'CentralAdminController@broadcast', ['auth', 'csrf']);
$router->post('/chat/messages/edit', 'ChatController@editMessage', ['auth', 'csrf']);
$router->get('/api/users/online-status', 'ChatController@getOnlineStatus', ['auth', 'activity']);
$router->get('/api/presence/ping', 'ChatController@pingPresence', ['auth', 'activity']);
$router->post('/chat/join', 'ChatController@joinRoom', ['auth', 'csrf', 'activity']);
